SELECT
  RESPUESTA
  FROM DET_EVAL_FRACCIONES
    WHERE EVALUACION_FRACCION_ID = 1
      AND ART_FRACC_RESPUESTA_ID = 61;

SELECT
  afr.*,
  def.RESPUESTA checked
FROM
  ART_FRACC_RESPUESTAS afr,
  DET_EVAL_FRACCIONES def
WHERE afr.ART_FRACC_RESPUESTA_ID = def.ART_FRACC_RESPUESTA_ID
      AND afr.ARTICULO_FRACCION_ID = 12
      AND def.EVALUACION_FRACCION_ID = 118096;