SELECT
  count(af.ARTICULO_FRACCION_ID)
FROM EVALUACIONES_FRACCIONES ef, ARTICULOS_FRACCIONES af
WHERE ef.ARTICULO_FRACCION_ID = af.ARTICULO_FRACCION_ID
  AND ef.EVALUACION_ARTICULO_ID = 1
ORDER BY af.ARTICULO_ID, af.NUMERO