SELECT
  aux.*,
  (
    CASE WHEN def.RESPUESTA > 0 THEN 1
      ELSE 0
    END
  ) AS checked
  FROM DET_EVAL_FRACCIONES def, (
    SELECT
      afr.ART_FRACC_RESPUESTA_ID,
      afr.ARTICULO_FRACCION_ID,
      afr.RESPUESTA,
      afr.VALOR,
      afr.ORDEN,
      afr.ESTATUS,
      afr.TIPO_CRITERIO_ID,
      ef.EVALUACION_FRACCION_ID
    FROM EVALUACIONES_FRACCIONES ef
      INNER JOIN ART_FRACC_RESPUESTAS afr
        ON ef.ARTICULO_FRACCION_ID = afr.ARTICULO_FRACCION_ID
    WHERE ef.EVALUACION_ID = 7544
          AND afr.ARTICULO_FRACCION_ID = 3
  ) aux
  WHERE def.EVALUACION_FRACCION_ID = aux.EVALUACION_FRACCION_ID
    AND def.ART_FRACC_RESPUESTA_ID = aux.ART_FRACC_RESPUESTA_ID
    ORDER BY aux.ORDEN;



